### ISSUE TITLE
width and height must be > 0

### ISSUE THREAD

**Issue by abadoliverco** [cooltechworks/ScratchView#20]
` java.lang.IllegalArgumentException: width and height must be > 0
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1074)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:1041)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:991)
        at android.graphics.Bitmap.createBitmap(Bitmap.java:952)
        at com.cooltechworks.views.ScratchTextView.onSizeChanged(ScratchTextView.java:175)
        at android.view.View.sizeChange(View.java:22602)
        at android.view.View.setFrame(View.java:22544)
        at android.widget.TextView.setFrame(TextView.java:7137)
        at android.view.View.layout(View.java:22404)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at androidx.viewpager.widget.ViewPager.onLayout(ViewPager.java:1775)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at androidx.constraintlayout.widget.ConstraintLayout.onLayout(ConstraintLayout.java:1915)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.layoutChild(CoordinatorLayout.java:1193)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayoutChild(CoordinatorLayout.java:880)
        at androidx.coordinatorlayout.widget.CoordinatorLayout.onLayout(CoordinatorLayout.java:899)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.LinearLayout.setChildFrame(LinearLayout.java:1812)
        at android.widget.LinearLayout.layoutVertical(LinearLayout.java:1656)
        at android.widget.LinearLayout.onLayout(LinearLayout.java:1565)
        at android.view.View.layout(View.java:22407)
        at android.view.ViewGroup.layout(ViewGroup.java:6589)
        at android.widget.FrameLayout.layoutChildren(FrameLayout.java:323)
        at android.widget.FrameLayout.onLayout(FrameLayout.java:261)
        at com.android.internal.policy.DecorView.onLayout(DecorView.java:1075)
        at android.view.View.layout(View.java:22407)
`

**Comment by Nikunj-Bisht12** [comment]
@abadoliverco did you find any solution for this?
